-- DPE public schema copied from Supabase. No production data or credentials.

-- Run only in the dedicated DPE Neon database.

CREATE SEQUENCE IF NOT EXISTS "butts_scholarship_submissions_id_seq";

CREATE SEQUENCE IF NOT EXISTS "weiss_scholarship_submissions_id_seq";

CREATE TABLE IF NOT EXISTS "scholarship_comments" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "name" text,
  "email" text,
  "comments" text NOT NULL,
  CHECK (((char_length(comments) >= 10) AND (char_length(comments) <= 10000))),
  CHECK (((email IS NULL) OR (char_length(email) <= 320))),
  CHECK (((name IS NULL) OR (char_length(name) <= 200))),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "weiss_scholarship_submissions" (
  "id" bigint DEFAULT nextval('weiss_scholarship_submissions_id_seq'::regclass) NOT NULL,
  "full_name" text NOT NULL,
  "application_file_path" text,
  "attendance_file_path" text,
  "intern_completion_file_path" text,
  "submission_time" timestamp with time zone DEFAULT now(),
  "reviewed" boolean DEFAULT false,
  "status" text DEFAULT 'Submitted - Unchecked'::text,
  "admin_notes" text,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "butts_scholarship_submissions" (
  "id" bigint DEFAULT nextval('butts_scholarship_submissions_id_seq'::regclass) NOT NULL,
  "full_name" text NOT NULL,
  "application_file_path" text,
  "attendance_file_path" text,
  "additional_requirements_file_path" text,
  "submission_time" timestamp with time zone DEFAULT now(),
  "reviewed" boolean DEFAULT false,
  "status" text DEFAULT 'Submitted - Unchecked'::text,
  "admin_notes" text,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "bleakley_scholarship_submissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "full_name" text NOT NULL,
  "application_file_path" text NOT NULL,
  "attendance_file_path" text NOT NULL,
  "test_completion_file_path" text NOT NULL,
  "submission_time" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "reviewed" boolean DEFAULT false,
  "status" text DEFAULT 'Submitted - Unchecked'::text,
  "admin_notes" text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "contact_form_submissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "full_name" text NOT NULL,
  "email" text NOT NULL,
  "message" text NOT NULL,
  "submission_time" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "read" boolean DEFAULT false NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "heartbeats" (
  "id" integer NOT NULL,
  "last_beat" timestamp with time zone,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "lemoine_scholarship_submissions" (
  "id" bigint DEFAULT nextval('weiss_scholarship_submissions_id_seq'::regclass) NOT NULL,
  "full_name" text NOT NULL,
  "application_file_path" text,
  "submission_time" timestamp with time zone DEFAULT now(),
  "reviewed" boolean DEFAULT false,
  "status" text DEFAULT 'Submitted - Unchecked'::text,
  "admin_notes" text,
  "created_at" timestamp with time zone DEFAULT now(),
  "resume_file_path" text,
  "transcript_file_path" text,
  "recommendation_file_path" text,
  PRIMARY KEY (id)
);
